### ISSUE TITLE
Schema files are not generated for record types that are only used inside streams

### ISSUE THREAD

**Issue by miyurud** [ballerina-platform/module-ballerinax-datamapper#130]
**Description:**
Refer this client function
https://github.com/ballerina-platform/module-ballerinax-googleapis.sheets/blob/2c2ffa793727f944e04acce8d801bc927ac228ee/gsheet/client.bal#L97
But this connecter doesn't generate File_schema.json inside resources.

**Steps to reproduce:**
Clone the connecter https://github.com/ballerina-platform/module-ballerinax-googleapis.sheets
Setup the repo and type `bal build -c --skip-tests` inside `gsheet` folder.

**Ballerina version::**
Ballerina Swan Lake Alpha 5

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by miyurud** [comment]
This was originally created by @SkNuwanTissera in the Ballerina Lang Repository as [Issue 30690](https://github.com/ballerina-platform/ballerina-lang/issues/30690).

**Comment by isuruRuhu** [comment]
This issue is fixed now in the server side data extractor. (Data extractor in Data mapper)
