### ISSUE TITLE
The compiler extension 'org.ballerinax.datamapper.DataMapperCompilerPlugin' failed to complete.

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/module-ballerinax-datamapper#200]
**Description:**
Experiencing below error when trying to build a ballerina project using `bal build` command. 

```
error: compilation failed: The compiler extension 'org.ballerinax.datamapper.DataMapperCompilerPlugin' failed to complete. class io.ballerina.compiler.api.impl.symbols.BallerinaCompilationErrorTypeSymbol cannot be cast to class io.ballerina.compiler.api.symbols.FunctionTypeSymbol (io.ballerina.compiler.api.impl.symbols.BallerinaCompilationErrorTypeSymbol and io.ballerina.compiler.api.symbols.FunctionTypeSymbol are in unnamed module of loader 'app')
```
Please find the ballerina project which gives the above error [here](https://drive.google.com/file/d/138maRQnRAZ2fuhS4kndlrahphRAQjoDb/view?usp=sharing)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by abeykoon** [comment]
We found that this issue is related to the method name generated by the connector. When a method name has a `-` in the middle, it generates this error. @aneeshafedo can confirm.

**Comment by aneeshafedo** [comment]
This error has occurred due to invalid  remote function names (Ex: `remote isolated function getcheckout-key()`) generated via Ballerina OpenAPI tool.  This [issue](https://github.com/ballerina-platform/ballerina-openapi/issues/467) is added at `ballerina-platform.ballerina-openapi` repository.
